version: '3.8'

services:
  api:
    build: ./api
    depends_on:
      - db
    networks:
      - forum-net
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forum-net

  thread:
    build: ./thread
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - forum-net
  
  sender:
    build: ./sender
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - forum-net



volumes:
  db-data:

networks:
  forum-net:
